### ISSUE TITLE
F-Droid inclusion and separate gradle flavor request

### ISSUE THREAD

**Issue by ClockGen** [massivemadness/Squircle-IDE#38] opened 2021-01-11 13:06 UTC
I'd like to include your app to F-Droid, which is a catalogue of FOSS apps and client and server software for its distribution. You can read more about F-Droid at http://f-droid.org/. As per inclusion policy, I must ask for your permission to do so. As for inclusion progress, you can track it here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8118.  
If you agree, I also must ask you for a separate gradle flavor without com.google.android.play.core library, which is not FOSS.

**Comment by massivemadness** [comment] 2021-01-11 13:32
Is that duplicate of https://gitlab.com/fdroid/rfp/-/issues/16016 ??
I need some time to upload images and update the description, I'll make it on holidays

**Comment by ClockGen** [comment] 2021-01-11 13:46
No, that one is a request for packaging, while the merge request is the actual packaging (or at least providing the f-droid build server with build instructions to build the app on the next run).

**Comment by alexanderadam** [comment] 2021-03-19 15:56
Can this issue be closed [since Brackeys IDE is available now](https://f-droid.org/en/packages/com.brackeys.ui/) or am I misunderstanding something?

**Comment by ClockGen** [comment] 2021-03-22 05:35
So far we've added it with a massive patch that removes play core library and it's respective code (it's useless anyway since it's used for in-app updates and F-Droid signs apks with it's own key), and this patch already proven to break at every update. So far I fixed it but mosy likely it'll keep breaking with every update.  
So a separate gradle flavor without this library would be greatly appreciated.

**Comment by massivemadness** [comment] 2021-03-22 07:34
@ClockGen I'm working on architecture improvements, I'll let you know when I make the separate flavor 👌

**Comment by massivemadness** [comment] 2021-05-28 15:26
@ClockGen I added a new gradle flavor called `fdroid`, you can use it for building the app

**Closed by massivemadness** 2021-05-28 15:26 UTC
Labels: feature

**Comment by TPS** [comment] 2021-06-27 04:52
v2021.1.3 has been published @ F-Droid 6/15/21!
